name: Live Chat CI/CD

on:
  push:
    branches:
      - main
      - 'feature/*'
  pull_request:
    branches:
      - main

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Install Frontend Dependencies
        run: |
          cd frontend
          npm install
          
      - name: Review Frontend Code
        run: |
          cd frontend
          npx eslint .
          
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Frontend Deployment to Vercel
      - name: Deploy Frontend to Vercel
        run: |
          cd frontend
          npm install
          npm run build
          vercel --prod --token ${{ secrets.VERCEL_TOKEN }}
